name: RunCronPyDateFolder

on:
   push
  #schedule:
  #  - cron: '*/3 * * * *' # runs at 12:00 UTC everyday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7.7' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute py script # run testfile.py to get the latest data
        run: python testfile.py
        
      - name: Run a inline script
        run: |
             echo The date and time is: 
             echo $(date)

          



